log26(a):=log(a)/log(26);
alphabet:["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"];
keyspace(length):=lreduce(lambda([i,j],create_list(sconcat(ielt,jelt),ielt,i,jelt,j)),makelist(alphabet,i,1,ceiling(log26(length))));
autokeys(length):=rand_selection(keyspace(length),length);
zip(list1,list2):=makelist([list1[i],list2[i]],i,1,min(length(list1),length(list2)));
auto_map(list):=block(listlen:length(list),if is(equal(listlen,0)) then return([]),keys:autokeys(listlen),listMap:zip(keys,list),push("stack_map",listMap));
auto_map(list1,list2):=(listlen1:length(list1),listlen2:length(list2),listlen:listlen1+listlen2,keys:autokeys(listlen),listMap1:zip(firstn(keys,listlen1),list1),list1:push("stack_map",listMap1),listMap2:zip(lastn(keys,listlen2),list2),list2:push("stack_map",listMap2),[list1,list2]);
r(n):=rand_with_prohib(-n,n,[0]);
